image: alpine

stages:
 - build
 - publish

build-pdf:
  image: raabf/latex-versions:texlive2018
  stage: build
  tags:
    - docker
  script:
    - lsb_release --all
    - latex --version
    - latexmk -pdf -xelatex cv.tex
  artifacts:
    paths:
      - ./cv.pdf

build-website:
  image: node:12-slim
  stage: build
  tags:
    - docker
  script:
    - cd website
    - npm ci
    - npm run build
    - npm run export
    - cp -r out ../public
  artifacts:
    paths:
      - public

pages:
  stage: publish
  dependencies:
    - build-pdf
    - build-website
  script:
    - mv cv.pdf public
  artifacts:
    paths:
      - public
  only:
    - master

