# This file is a template, and might need editing before it works on your project.
# use docker image with latex preinstalled
# since there is no official latex image, use https://github.com/blang/latex-docker
# possible alternative: https://github.com/natlownes/docker-latex
image: alpine

stages:
 - build
 - publish

make_texlive2018:
  image: raabf/latex-versions:texlive2018
  stage: build
  tags:
    - docker
  script:
    - make all
  artifacts:
    paths:
      - "*.pdf"

pages:
  stage: publish
  dependencies: 
    - compile
  script:
    - mkdir public
    - mv cv.pdf public
  artifacts:
    paths:
      - public
  only:
    - master
