image: alpine

stages:
 - build
 - publish

compile:
  image: raabf/latex-versions:texlive2018
  stage: build
  tags:
    - docker
  script:
    - lsb_release --all
    - latex --version
    - latexmk -pdf -xelatex cv.tex"
  artifacts:
    paths:
      - ./cv.pdf

pages:
  stage: publish
  dependencies: 
    - compile
  script:
    - mkdir public
    - mv cv.pdf public
  artifacts:
    paths:
      - public
  only:
    - master
